// Generated by tools/fetch-photos.mjs from tools/photos.json. Photos via Wikimedia Commons (see credits).
window.TIMESCOPE_PHOTOS = [
 {
  "id": "eiffel-1888",
  "place": "Paris, France",
  "lat": 48.8584,
  "lng": 2.2945,
  "year": 1888,
  "fact": "The Eiffel Tower under construction, a few months before the 1889 World's Fair.",
  "src": "photos/eiffel-1888.jpg",
  "credit": {
   "artist": "Louis-Emile Durandelle",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Louis-Emile_Durandelle,_The_Eiffel_Tower_-_State_of_the_Construction,_1888.jpg"
  }
 },
 {
  "id": "sf-fire-1906",
  "place": "San Francisco, USA",
  "lat": 37.7929,
  "lng": -122.4079,
  "year": 1906,
  "fact": "Smoke rises over Sacramento Street hours after the great 1906 earthquake.",
  "src": "photos/sf-fire-1906.jpg",
  "credit": {
   "artist": "Arnold Genthe",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:San_Francisco_Fire_Sacramento_Street_1906-04-18.jpg"
  }
 },
 {
  "id": "flatiron-1903",
  "place": "New York City, USA",
  "lat": 40.7411,
  "lng": -73.9897,
  "year": 1903,
  "fact": "The brand-new Flatiron Building, one of New York's first skyscrapers.",
  "src": "photos/flatiron-1903.jpg",
  "credit": {
   "artist": "Unknown author",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Flatiron_Building_NYC_c1903.jpg"
  }
 },
 {
  "id": "tower-bridge-1892",
  "place": "London, UK",
  "lat": 51.5055,
  "lng": -0.0754,
  "year": 1892,
  "fact": "Tower Bridge halfway built. It opened in 1894.",
  "src": "photos/tower-bridge-1892.jpg",
  "credit": {
   "artist": "Unknown author",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Tower_bridge_works_1892.jpg"
  }
 },
 {
  "id": "first-flight-1903",
  "place": "Kitty Hawk, North Carolina, USA",
  "lat": 36.0146,
  "lng": -75.668,
  "year": 1903,
  "fact": "The Wright brothers' first powered flight lasted 12 seconds.",
  "src": "photos/first-flight-1903.jpg",
  "credit": {
   "artist": "John T. Daniels",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:First_flight3.jpg"
  }
 },
 {
  "id": "machu-picchu-1912",
  "place": "Machu Picchu, Peru",
  "lat": -13.1631,
  "lng": -72.545,
  "year": 1912,
  "fact": "Hiram Bingham's expedition photographed the ruins after clearing the jungle.",
  "src": "photos/machu-picchu-1912.jpg",
  "credit": {
   "artist": "Hiram Bingham III",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Machu_Picchu.png"
  }
 },
 {
  "id": "samarkand-1911",
  "place": "Samarkand, Uzbekistan",
  "lat": 39.6548,
  "lng": 66.9757,
  "year": 1911,
  "fact": "An early color photo by Prokudin-Gorsky, made from three black-and-white exposures.",
  "src": "photos/samarkand-1911.jpg",
  "credit": {
   "artist": "Sergei Prokudin-Gorskii",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Gorskii_21808u.jpg"
  }
 },
 {
  "id": "empire-state-1930",
  "place": "New York City, USA",
  "lat": 40.7484,
  "lng": -73.9857,
  "year": 1930,
  "fact": "Lewis Hine photographed the Empire State Building as it rose, floor by floor.",
  "src": "photos/empire-state-1930.jpg",
  "credit": {
   "artist": "Lewis Hine",
   "license": "CC0",
   "page": "https://commons.wikimedia.org/wiki/File:Empire_State_Building_MET_DP106404.jpg"
  }
 },
 {
  "id": "chicago-fair-1893",
  "place": "Chicago, USA",
  "lat": 41.7897,
  "lng": -87.5836,
  "year": 1893,
  "fact": "The 'White City' of the World's Columbian Exposition.",
  "src": "photos/chicago-fair-1893.jpg",
  "credit": {
   "artist": "William Henry Jackson",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Court_of_Honor,_Looking_West,_William_Henry_Jackson,_1893.jpg"
  }
 },
 {
  "id": "sydney-bridge-1930",
  "place": "Sydney, Australia",
  "lat": -33.8523,
  "lng": 151.2108,
  "year": 1930,
  "fact": "The two halves of the Harbour Bridge arch reaching toward each other.",
  "src": "photos/sydney-bridge-1930.jpg",
  "credit": {
   "artist": "Tyrell Collection",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Sydney_Harbour_Bridge_under_construction.jpg"
  }
 },
 {
  "id": "apollo11-1969",
  "place": "Kennedy Space Center, Florida, USA",
  "lat": 28.6083,
  "lng": -80.6041,
  "year": 1969,
  "fact": "Apollo 11 lifts off for the first Moon landing.",
  "src": "photos/apollo11-1969.jpg",
  "credit": {
   "artist": "NASA; restored by Michel Vuijlsteke",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Apollo_11_Launch2.jpg"
  }
 },
 {
  "id": "rushmore-1932",
  "place": "Mount Rushmore, South Dakota, USA",
  "lat": 43.8791,
  "lng": -103.4591,
  "year": 1932,
  "fact": "Workers carving George Washington's face.",
  "src": "photos/rushmore-1932.jpg",
  "credit": {
   "artist": "Rise Studio, Rapid City, S. Dak. Copyright not renewed.",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Mount_Rushmore2.jpg"
  }
 },
 {
  "id": "dust-bowl-1936",
  "place": "Dallas, South Dakota, USA",
  "lat": 43.2356,
  "lng": -99.5129,
  "year": 1936,
  "fact": "Farm machinery buried by drifting soil during the Dust Bowl.",
  "src": "photos/dust-bowl-1936.jpg",
  "credit": {
   "artist": "Sloan (?)",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Dust_Bowl_-_Dallas,_South_Dakota_1936.jpg"
  }
 },
 {
  "id": "golden-spike-1869",
  "place": "Promontory Summit, Utah, USA",
  "lat": 41.618,
  "lng": -112.551,
  "year": 1869,
  "fact": "The first transcontinental railroad in the US is completed.",
  "src": "photos/golden-spike-1869.jpg",
  "credit": {
   "artist": "Andrew J. Russell / Adam Cuerden",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:East_and_West_Shaking_hands_at_the_laying_of_last_rail_Union_Pacific_Railroad_-_Restoration.jpg"
  }
 },
 {
  "id": "hoover-dam-1934",
  "place": "Hoover Dam, Nevada/Arizona, USA",
  "lat": 36.016,
  "lng": -114.7377,
  "year": 1934,
  "fact": "Intake towers rising at the half-built Hoover Dam.",
  "src": "photos/hoover-dam-1934.jpg",
  "credit": {
   "artist": "National Archives, Herbert Hoover Presidential Library and Museum",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Construction_Intake_Towers_Hoover_Dam_1934.jpg"
  }
 },
 {
  "id": "johnstown-1889",
  "place": "Johnstown, Pennsylvania, USA",
  "lat": 40.3267,
  "lng": -78.922,
  "year": 1889,
  "fact": "Wreckage after a dam failure sent a wall of water through Johnstown.",
  "src": "photos/johnstown-1889.jpg",
  "credit": {
   "artist": "Miscellaneous Items in High Demand, PPOC, Library of Congress",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Johnstown_Flood,_1889-_Landmark_-26_LCCN2005683591.jpg"
  }
 },
 {
  "id": "paris-flood-1910",
  "place": "Paris, France",
  "lat": 48.848,
  "lng": 2.3716,
  "year": 1910,
  "fact": "The Great Flood of Paris turned streets into canals.",
  "src": "photos/paris-flood-1910.jpg",
  "credit": {
   "artist": "Anonyme, photographe",
   "license": "CC0",
   "page": "https://commons.wikimedia.org/wiki/File:Crue_de_la_Seine,_rue_de_Lyon,_12%C3%A8me_arrondissement,_Paris._Inondation_1910._PH8640.jpg"
  }
 },
 {
  "id": "taj-mahal-1865",
  "place": "Agra, India",
  "lat": 27.1751,
  "lng": 78.0421,
  "year": 1865,
  "fact": "Photographed by Samuel Bourne, who spent years documenting India in the 1860s.",
  "src": "photos/taj-mahal-1865.jpg",
  "credit": {
   "artist": "Samuel Bourne",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:KITLV_91973_-_Samuel_Bourne_-_Taj_Mahal_at_Agra_in_India_-_Around_1860.tif"
  }
 },
 {
  "id": "sphinx-1876",
  "place": "Giza, Egypt",
  "lat": 29.9753,
  "lng": 31.1376,
  "year": 1876,
  "fact": "The Great Sphinx, still half-buried in sand.",
  "src": "photos/sphinx-1876.jpg",
  "credit": {
   "artist": "Félix Bonfils",
   "license": "CC0",
   "page": "https://commons.wikimedia.org/wiki/File:Giza,_Sphynx_and_funerary_temple_of_Khafre,_19th_century_pictures,_1875-1877,_photo_8_of_9_-_Archivio_fotografico_Museo_Egizio,_Turin_INV01_011.jpg"
  }
 },
 {
  "id": "titanic-1912",
  "place": "Southampton, UK",
  "lat": 50.897,
  "lng": -1.4,
  "year": 1912,
  "fact": "Titanic leaves Southampton on her first and only voyage.",
  "src": "photos/titanic-1912.jpg",
  "credit": {
   "artist": "Francis Godolphin Osbourne Stuart",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:RMS_Titanic_3.jpg"
  }
 },
 {
  "id": "great-wall-1907",
  "place": "Great Wall, near Beijing, China",
  "lat": 40.3587,
  "lng": 116.0204,
  "year": 1907,
  "fact": "The Great Wall photographed by Herbert Ponting.",
  "src": "photos/great-wall-1907.jpg",
  "credit": {
   "artist": "Herbert Ponting",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Greatwall_large.jpg"
  }
 },
 {
  "id": "rio-1910",
  "place": "Rio de Janeiro, Brazil",
  "lat": -22.897,
  "lng": -43.181,
  "year": 1910,
  "fact": "Avenida Central, the grand new boulevard of Brazil's capital at the time.",
  "src": "photos/rio-1910.jpg",
  "credit": {
   "artist": "Núcleo de digitalização / IMS",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Avenida_Central,_atual_Rio_Branco;_%C3%A0_direita,_o_Monumento_a_Visconde_de_Mau%C3%A1_(007_IMG_2001).jpg"
  }
 },
 {
  "id": "buenos-aires-1894",
  "place": "Buenos Aires, Argentina",
  "lat": -34.6088,
  "lng": -58.3765,
  "year": 1894,
  "fact": "Buildings being demolished to open Avenida de Mayo.",
  "src": "photos/buenos-aires-1894.jpg",
  "credit": {
   "artist": "Unknown author",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Apetura_avenida_mayo.jpg"
  }
 },
 {
  "id": "st-petersburg-1900",
  "place": "Saint Petersburg, Russia",
  "lat": 59.9338,
  "lng": 30.3345,
  "year": 1900,
  "fact": "A horse-drawn tram on Nevsky Prospect.",
  "src": "photos/st-petersburg-1900.jpg",
  "credit": {
   "artist": "Karl Bulla",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Horsetram_on_Nevsky_Prospect_54.jpg"
  }
 },
 {
  "id": "delhi-durbar-1903",
  "place": "Delhi, India",
  "lat": 28.7297,
  "lng": 77.1965,
  "year": 1903,
  "fact": "The Delhi Durbar celebrated Edward VII becoming Emperor of India.",
  "src": "photos/delhi-durbar-1903.jpg",
  "credit": {
   "artist": "Unknown author",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Delhi_Durbar_of_1903_-_LIFE_(2).jpg"
  }
 },
 {
  "id": "colosseum-1846",
  "place": "Rome, Italy",
  "lat": 41.8902,
  "lng": 12.4922,
  "year": 1846,
  "fact": "One of the earliest photographs of the Colosseum.",
  "src": "photos/colosseum-1846.jpg",
  "credit": {
   "artist": "Calvert Jones",
   "license": "CC0",
   "page": "https://commons.wikimedia.org/wiki/File:67._Colosseum,_Rome,_Second_View_MET_DP312745.jpg"
  }
 },
 {
  "id": "capitol-1861",
  "place": "Washington, D.C., USA",
  "lat": 38.8899,
  "lng": -77.0091,
  "year": 1861,
  "fact": "The US Capitol's new dome, unfinished at the start of the Civil War.",
  "src": "photos/capitol-1861.jpg",
  "credit": {
   "artist": "Miscellaneous Items in High Demand, PPOC, Library of Congress",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Capitol_dome_construction_LCCN2009631449.jpg"
  }
 },
 {
  "id": "chicago-fire-1871",
  "place": "Chicago, USA",
  "lat": 41.8837,
  "lng": -87.632,
  "year": 1871,
  "fact": "The Great Chicago Fire burned more than three square miles of the city.",
  "src": "photos/chicago-fire-1871.jpg",
  "credit": {
   "artist": "Clark, C. R. (Charles R.)",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Chicago_Fire_of_1871,_Court_House_Through_Ruins_of_Fifth_National_Bank_(NBY_1364).jpg"
  }
 },
 {
  "id": "moscow-1893",
  "place": "Moscow, Russia",
  "lat": 55.7525,
  "lng": 37.6231,
  "year": 1893,
  "fact": "Red Square's monument to Minin and Pozharsky, photographed by Alexey Mazurin.",
  "src": "photos/moscow-1893.jpg",
  "credit": {
   "artist": "Aleksey Mazurin",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0._%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%B0%D1%8F_%D0%BF%D0%BB._%D0%9F%D0%B0%D0%BC%D1%8F%D1%82%D0%BD%D0%B8%D0%BA_%D0%9C%D0%B8%D0%BD%D0%B8%D0%BD%D1%83_%D0%B8_%D0%9F%D0%BE%D0%B6%D0%B0%D1%80%D1%81%D0%BA%D0%BE%D0%BC%D1%83._(c)%D0%9C%D0%B0%D0%B7%D1%83%D1%80%D0%B8%D0%BD_%D0%90.%D0%A1._1900-%D0%B5%D0%B3%D0%B3_%D0%93%D0%98%D0%9C_e1.jpg"
  }
 },
 {
  "id": "hagia-sophia-1897",
  "place": "Istanbul, Turkey",
  "lat": 41.0086,
  "lng": 28.9802,
  "year": 1897,
  "fact": "Hagia Sophia in Constantinople, as Istanbul was then known.",
  "src": "photos/hagia-sophia-1897.jpg",
  "credit": {
   "artist": "Unknown author",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Hagia_Sophia,_Constantinople,_Turkey,_ca._1897.jpg"
  }
 },
 {
  "id": "angkor-1866",
  "place": "Angkor Wat, Cambodia",
  "lat": 13.4125,
  "lng": 103.867,
  "year": 1866,
  "fact": "John Thomson took some of the first photographs of Angkor Wat.",
  "src": "photos/angkor-1866.jpg",
  "credit": {
   "artist": "Unknown",
   "license": "CC BY 4.0",
   "page": "https://commons.wikimedia.org/wiki/File:Nakhon_Thom_(Angkor_Wat),_Cambodia._Wellcome_L0055705.jpg"
  }
 },
 {
  "id": "nihonbashi-1911",
  "place": "Tokyo, Japan",
  "lat": 35.684,
  "lng": 139.7745,
  "year": 1911,
  "fact": "Crowds visit the brand-new stone Nihonbashi bridge.",
  "src": "photos/nihonbashi-1911.jpg",
  "credit": {
   "artist": "不明 unknown",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:NewlyBuilt_Nihonbashi_1911_Tokyo.jpg"
  }
 },
 {
  "id": "cape-town-1897",
  "place": "Cape Town, South Africa",
  "lat": -33.9227,
  "lng": 18.4209,
  "year": 1897,
  "fact": "Queen Victoria's Diamond Jubilee procession on Adderley Street.",
  "src": "photos/cape-town-1897.jpg",
  "credit": {
   "artist": "Lieut. William J. Frazer, R.N.R., H.M.S. St George. Frazer died on 2 May 1938. Ship photog",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Adderley_Street,_Cape_Town,_South_Africa,_22_June_1897_H0061-L351324055.jpg"
  }
 },
 {
  "id": "jerusalem-1900",
  "place": "Jerusalem",
  "lat": 31.7765,
  "lng": 35.228,
  "year": 1900,
  "fact": "Just inside the Jaffa Gate of Jerusalem's Old City.",
  "src": "photos/jerusalem-1900.jpg",
  "credit": {
   "artist": "American Colony (Jerusalem). Photo Dept., photographer",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:View_inside_Jaffa_Gate,_Jerusalem._between_1898_and_1907._matpc.08601.jpg"
  }
 },
 {
  "id": "amsterdam-1895",
  "place": "Amsterdam, Netherlands",
  "lat": 52.3731,
  "lng": 4.8926,
  "year": 1895,
  "fact": "Dam Square in a photochrom, an early way of turning photos into color prints.",
  "src": "photos/amsterdam-1895.jpg",
  "credit": {
   "artist": "Detroit Publishing Co., under license from Photoglob Zürich",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Dam_square,_Amsterdam,_North_Holland,_the_Netherlands,_1890s.jpg"
  }
 },
 {
  "id": "sagrada-1905",
  "place": "Barcelona, Spain",
  "lat": 41.4036,
  "lng": 2.1744,
  "year": 1905,
  "fact": "Gaudí's Sagrada Família in 1905. It's still being finished today.",
  "src": "photos/sagrada-1905.jpg",
  "credit": {
   "artist": "Baldomer Gili i Roig",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Baldomer_Gili_Roig._La_Sagrada_Fam%C3%ADlia,_1905_Copia_moderna_del_negatiu_original_de_vidre.jpg"
  }
 },
 {
  "id": "neuschwanstein-1897",
  "place": "Neuschwanstein Castle, Germany",
  "lat": 47.5576,
  "lng": 10.7498,
  "year": 1897,
  "fact": "The fairy-tale castle that inspired Disney, only a few years after completion.",
  "src": "photos/neuschwanstein-1897.jpg",
  "credit": {
   "artist": "Unknown author",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Neuschwanstein_Castle_LOC_print_rotated.jpg"
  }
 },
 {
  "id": "havana-1903",
  "place": "Havana, Cuba",
  "lat": 23.1383,
  "lng": -82.3597,
  "year": 1903,
  "fact": "The Paseo del Prado, Havana's grand promenade.",
  "src": "photos/havana-1903.jpg",
  "credit": {
   "artist": "AnonymousUnknown author",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Havana_-_Prado_Avenue.jpg"
  }
 },
 {
  "id": "melbourne-1890",
  "place": "Melbourne, Australia",
  "lat": -37.8143,
  "lng": 144.972,
  "year": 1890,
  "fact": "Collins Street during the 'Marvellous Melbourne' boom years.",
  "src": "photos/melbourne-1890.jpg",
  "credit": {
   "artist": "Possibly Charles Cheney Simpson",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Collins_Street,_near_the_corner_of_Spring_Street.jpg"
  }
 },
 {
  "id": "mexico-city-1907",
  "place": "Mexico City, Mexico",
  "lat": 19.4344,
  "lng": -99.1332,
  "year": 1907,
  "fact": "The Metropolitan Cathedral on the Zócalo, the largest cathedral in the Americas.",
  "src": "photos/mexico-city-1907.jpg",
  "credit": {
   "artist": "(Not given)",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Cathedral_of_Mexico_City,_Mexico,_ca.1905-1910_(CHS-667).jpg"
  }
 },
 {
  "id": "obama-inauguration-2009",
  "place": "National Mall, Washington, D.C., USA",
  "lat": 38.8893,
  "lng": -77.02,
  "year": 2009,
  "fact": "About 1.8 million people packed the National Mall for Barack Obama's first inauguration.",
  "src": "photos/obama-inauguration-2009.jpg",
  "credit": {
   "artist": "Senior Master Sgt. Thomas Meneguin, USAF",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Crowd_at_National_Mall_for_Obama_inauguration_1-20-09_hires_090120-F-6184M-007a.jpg"
  }
 },
 {
  "id": "trump-inauguration-2017",
  "place": "U.S. Capitol, Washington, D.C., USA",
  "lat": 38.8898,
  "lng": -77.0106,
  "year": 2017,
  "fact": "Donald Trump waves to the crowd after being sworn in as the 45th president.",
  "src": "photos/trump-inauguration-2017.jpg",
  "credit": {
   "artist": "Staff Sgt. Marianique Santos",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Obama_hands_over_presidency_to_Trump_at_58th_Presidential_Inauguration_170120-D-NA975-0804.jpg"
  }
 },
 {
  "id": "biden-inauguration-2021",
  "place": "U.S. Capitol, Washington, D.C., USA",
  "lat": 38.8898,
  "lng": -77.0106,
  "year": 2021,
  "fact": "Joe Biden's inauguration was held with masks and a tiny crowd during the COVID-19 pandemic.",
  "src": "photos/biden-inauguration-2021.jpg",
  "credit": {
   "artist": "Chairman of the Joint Chiefs of Staff from Washington D.C, United States",
   "license": "CC BY 2.0",
   "page": "https://commons.wikimedia.org/wiki/File:210120-D-WD757-1595_Kamala_Harris_claps_for_Joe_Biden_at_his_inauguration_(50860518413).jpg"
  }
 },
 {
  "id": "lula-inauguration-2023",
  "place": "Brasília, Brazil",
  "lat": -15.7998,
  "lng": -47.8645,
  "year": 2023,
  "fact": "Lula was sworn in as Brazil's president for the third time.",
  "src": "photos/lula-inauguration-2023.jpg",
  "credit": {
   "artist": "Sintegrity",
   "license": "CC BY-SA 4.0",
   "page": "https://commons.wikimedia.org/wiki/File:Bras%C3%ADlia_-_Posse_de_Luiz_In%C3%A1cio_Lula_da_Silva_2023_(114).jpg"
  }
 },
 {
  "id": "portal-2024",
  "place": "Flatiron District, New York City, USA",
  "lat": 40.7406,
  "lng": -73.9894,
  "year": 2024,
  "fact": "The Portal livestreamed New York and Dublin to each other around the clock.",
  "src": "photos/portal-2024.jpg",
  "credit": {
   "artist": "Rhododendrites",
   "license": "CC BY-SA 4.0",
   "page": "https://commons.wikimedia.org/wiki/File:NYC_Portal_(51331).jpg"
  }
 },
 {
  "id": "endeavour-2012",
  "place": "Inglewood, Los Angeles, USA",
  "lat": 33.9601,
  "lng": -118.3441,
  "year": 2012,
  "fact": "Space Shuttle Endeavour crawled 12 miles through Los Angeles streets to its museum.",
  "src": "photos/endeavour-2012.jpg",
  "credit": {
   "artist": "Pedro Szekely from Los Angeles, USA",
   "license": "CC BY-SA 2.0",
   "page": "https://commons.wikimedia.org/wiki/File:Space_Shuttle_Endeavour_in_Los_Angeles_-_2012_(37919560104).jpg"
  }
 },
 {
  "id": "notre-dame-fire-2019",
  "place": "Notre-Dame, Paris, France",
  "lat": 48.853,
  "lng": 2.3499,
  "year": 2019,
  "fact": "Notre-Dame's spire in flames, shortly before it collapsed.",
  "src": "photos/notre-dame-fire-2019.jpg",
  "credit": {
   "artist": "LEVRIER Guillaume",
   "license": "CC BY-SA 4.0",
   "page": "https://commons.wikimedia.org/wiki/File:Fl%C3%A8che_en_feu_-_Spire_on_Fire.jpeg"
  }
 },
 {
  "id": "paris-olympics-2024",
  "place": "River Seine, Paris, France",
  "lat": 48.858,
  "lng": 2.3,
  "year": 2024,
  "fact": "The first Olympic opening ceremony held outside a stadium, with athletes on boats along the Seine.",
  "src": "photos/paris-olympics-2024.jpg",
  "credit": {
   "artist": "Sgt. 1st Class Kulani Lakanaria",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:U.S._Olympic_Team_participates_in_2024_Opening_Ceremonies_in_Paris_(240726-A-UW671-1010).jpg"
  }
 },
 {
  "id": "coronation-2023",
  "place": "Buckingham Palace, London, UK",
  "lat": 51.5014,
  "lng": -0.1419,
  "year": 2023,
  "fact": "The royal family on the palace balcony after the coronation of King Charles III.",
  "src": "photos/coronation-2023.jpg",
  "credit": {
   "artist": "Pail Clarke, Department for Culture, Media &amp; Sport",
   "license": "OGL 3",
   "page": "https://commons.wikimedia.org/wiki/File:2023_Coronation,_Buckingham_Palace_Balcony.jpg"
  }
 },
 {
  "id": "berlin-wall-1989",
  "place": "Brandenburg Gate, Berlin, Germany",
  "lat": 52.5163,
  "lng": 13.3777,
  "year": 1989,
  "fact": "East and West Germans meet at a new gap in the Berlin Wall by the Brandenburg Gate.",
  "src": "photos/berlin-wall-1989.jpg",
  "credit": {
   "artist": "SSGT F. Lee Corkran",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Crane_removed_part_of_Wall_Brandenburg_Gate.jpg"
  }
 },
 {
  "id": "chile-mine-rescue-2010",
  "place": "San José Mine, near Copiapó, Chile",
  "lat": -27.15,
  "lng": -70.5,
  "year": 2010,
  "fact": "Rescuers prepare to lift 33 trapped miners after 69 days underground.",
  "src": "photos/chile-mine-rescue-2010.jpg",
  "credit": {
   "artist": "Secretaria de Comunicaciones from Chile",
   "license": "CC BY 2.0",
   "page": "https://commons.wikimedia.org/wiki/File:Chile_Mine_Rescue_(5075429001).jpg"
  }
 },
 {
  "id": "eyjafjallajokull-2010",
  "place": "Eyjafjallajökull, Iceland",
  "lat": 63.6314,
  "lng": -19.6083,
  "year": 2010,
  "fact": "The Icelandic eruption whose ash cloud grounded flights across Europe.",
  "src": "photos/eyjafjallajokull-2010.jpg",
  "credit": {
   "artist": "Bjarki Sigursveinsson",
   "license": "CC BY-SA 3.0",
   "page": "https://commons.wikimedia.org/wiki/File:Eyjafjallaj%C3%B6kull_17-4-2010.jpg"
  }
 },
 {
  "id": "beijing-olympics-2008",
  "place": "Beijing National Stadium, China",
  "lat": 39.9916,
  "lng": 116.3906,
  "year": 2008,
  "fact": "The opening ceremony of the Beijing Olympics in the 'Bird's Nest' stadium.",
  "src": "photos/beijing-olympics-2008.jpg",
  "credit": {
   "artist": "Tim Hipps, U.S. Army",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Li_Ling_during_the_Opening_Ceremony_of_the_2008_Olympic_Games.jpg"
  }
 },
 {
  "id": "tahrir-square-2011",
  "place": "Tahrir Square, Cairo, Egypt",
  "lat": 30.0444,
  "lng": 31.2357,
  "year": 2011,
  "fact": "Crowds greet soldiers in Tahrir Square during Egypt's 2011 revolution.",
  "src": "photos/tahrir-square-2011.jpg",
  "credit": {
   "artist": "Alisdare Hickson from Canterbury, United Kingdom",
   "license": "CC BY-SA 2.0",
   "page": "https://commons.wikimedia.org/wiki/File:Tahrir_Square_29_January_2011_-_%22The_people_and_the_army_are_one_hand%22_(40339040312).jpg"
  }
 },
 {
  "id": "rio-olympics-2016",
  "place": "Maracanã Stadium, Rio de Janeiro, Brazil",
  "lat": -22.9121,
  "lng": -43.2302,
  "year": 2016,
  "fact": "The opening ceremony of the first Olympics held in South America.",
  "src": "photos/rio-olympics-2016.jpg",
  "credit": {
   "artist": "Agência Brasil",
   "license": "CC BY 3.0 br",
   "page": "https://commons.wikimedia.org/wiki/File:2016_Summer_Olympics_opening_ceremony_1035369-olimpiadas_abertura-2902.jpg"
  }
 },
 {
  "id": "starship-2023",
  "place": "Starbase, Boca Chica, Texas, USA",
  "lat": 25.9972,
  "lng": -97.1566,
  "year": 2023,
  "fact": "SpaceX's giant Super Heavy booster on its launch pad in South Texas.",
  "src": "photos/starship-2023.jpg",
  "credit": {
   "artist": "Mobilus In Mobili",
   "license": "CC BY-SA 2.0",
   "page": "https://commons.wikimedia.org/wiki/File:SpaceX_Starship_Superheavy_Testing_February_2023.jpg"
  }
 },
 {
  "id": "hiroshima-visit-2016",
  "place": "Hiroshima, Japan",
  "lat": 34.3915,
  "lng": 132.453,
  "year": 2016,
  "fact": "Barack Obama became the first sitting US president to visit Hiroshima.",
  "src": "photos/hiroshima-visit-2016.jpg",
  "credit": {
   "artist": "White House",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Barack_Obama_and_Shinzo_Abe_at_Hiroshima_Peace_Memorial_Park.jpg"
  }
 },
 {
  "id": "dmz-summit-2019",
  "place": "Panmunjom, Korean DMZ",
  "lat": 37.9559,
  "lng": 126.6772,
  "year": 2019,
  "fact": "Donald Trump became the first sitting US president to step into North Korea.",
  "src": "photos/dmz-summit-2019.jpg",
  "credit": {
   "artist": "Harry Harris",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Donald_Trump_and_Kim_Jong_Un_after_DMZ_Summit.jpg"
  }
 },
 {
  "id": "katrina-2005",
  "place": "New Orleans, Louisiana, USA",
  "lat": 29.9511,
  "lng": -90.0715,
  "year": 2005,
  "fact": "Much of New Orleans was still underwater days after Hurricane Katrina.",
  "src": "photos/katrina-2005.jpg",
  "credit": {
   "artist": "U.S. Navy photo by Gary Nichols",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:US_Navy_050902-N-5328N-228_Four_days_after_Hurricane_Katrina_made_landfall_on_the_Gulf_Coast,_many_parts_of_New_Orleans_remain_flooded.jpg"
  }
 },
 {
  "id": "artemis-2022",
  "place": "Kennedy Space Center, Florida, USA",
  "lat": 28.6272,
  "lng": -80.6208,
  "year": 2022,
  "fact": "Artemis I launched NASA's program to send astronauts back to the Moon.",
  "src": "photos/artemis-2022.jpg",
  "credit": {
   "artist": "NASA/STEVEN SEIPEL",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Launch_of_Artemis_1_(KSC_20221115_Artemis_I_Launch-2).jpg"
  }
 },
 {
  "id": "pyeongchang-2018",
  "place": "PyeongChang, South Korea",
  "lat": 37.6663,
  "lng": 128.6992,
  "year": 2018,
  "fact": "The opening ceremony of the PyeongChang Winter Olympics.",
  "src": "photos/pyeongchang-2018.jpg",
  "credit": {
   "artist": "Korea.net",
   "license": "CC BY-SA 2.0",
   "page": "https://commons.wikimedia.org/wiki/File:PyeongChang_Olympic_Opening_Ceremony_14.jpg"
  }
 },
 {
  "id": "modi-oath-2014",
  "place": "Rashtrapati Bhavan, New Delhi, India",
  "lat": 28.6143,
  "lng": 77.1994,
  "year": 2014,
  "fact": "Narendra Modi takes the oath of office as India's prime minister.",
  "src": "photos/modi-oath-2014.jpg",
  "credit": {
   "artist": "Prime Minister's Office",
   "license": "GODL-India",
   "page": "https://commons.wikimedia.org/wiki/File:The_President,_Shri_Pranab_Mukherjee_administering_the_oath_of_office_of_the_Prime_Minister_to_Shri_Narendra_Modi,_at_a_Swearing-in_Ceremony,_at_Rashtrapati_Bhavan,_in_New_Delhi_on_May_26,_2014.jpg"
  }
 },
 {
  "id": "london-olympics-2012",
  "place": "Olympic Park, London, UK",
  "lat": 51.5383,
  "lng": -0.0166,
  "year": 2012,
  "fact": "The Olympic Stadium lit up on the night of the London 2012 opening ceremony.",
  "src": "photos/london-olympics-2012.jpg",
  "credit": {
   "artist": "Alexander Kachkaev",
   "license": "CC BY 2.0",
   "page": "https://commons.wikimedia.org/wiki/File:Olympic_stadium_and_The_Orbit_during_London_Olympics_opening_ceremony_(2012-07-27)_2.jpg"
  }
 },
 {
  "id": "skytree-2010",
  "place": "Tokyo, Japan",
  "lat": 35.7101,
  "lng": 139.8107,
  "year": 2010,
  "fact": "Tokyo Skytree halfway built. It became the world's tallest tower.",
  "src": "photos/skytree-2010.jpg",
  "credit": {
   "artist": "yuiseki aoba",
   "license": "CC BY 2.0",
   "page": "https://commons.wikimedia.org/wiki/File:Tokyo_Skytree_under_construction_-_Jan_16,_2010.jpg"
  }
 },
 {
  "id": "ever-given-2021",
  "place": "Suez Canal, Egypt",
  "lat": 30.0176,
  "lng": 32.58,
  "year": 2021,
  "fact": "The container ship Ever Given, stuck sideways across the Suez Canal, seen from the space station.",
  "src": "photos/ever-given-2021.jpg",
  "credit": {
   "artist": "NASA JSC ISS image library",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Ever_Given_in_Suez_Canal_viewed_from_ISS.jpg"
  }
 }
];
