// Generated by tools/fetch-photos.mjs from tools/photos.json. Photos via Wikimedia Commons (see credits).
window.TIMESCOPE_PHOTOS = [
 {
  "id": "eiffel-1888",
  "place": "Paris, France",
  "lat": 48.8584,
  "lng": 2.2945,
  "year": 1888,
  "fact": "The Eiffel Tower under construction, a few months before the 1889 World's Fair.",
  "src": "photos/eiffel-1888.jpg",
  "credit": {
   "artist": "Louis-Emile Durandelle",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Louis-Emile_Durandelle,_The_Eiffel_Tower_-_State_of_the_Construction,_1888.jpg"
  }
 },
 {
  "id": "sf-fire-1906",
  "place": "San Francisco, USA",
  "lat": 37.7929,
  "lng": -122.4079,
  "year": 1906,
  "fact": "Smoke rises over Sacramento Street hours after the great 1906 earthquake.",
  "src": "photos/sf-fire-1906.jpg",
  "credit": {
   "artist": "Arnold Genthe",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:San_Francisco_Fire_Sacramento_Street_1906-04-18.jpg"
  }
 },
 {
  "id": "flatiron-1903",
  "place": "New York City, USA",
  "lat": 40.7411,
  "lng": -73.9897,
  "year": 1903,
  "fact": "The brand-new Flatiron Building, one of New York's first skyscrapers.",
  "src": "photos/flatiron-1903.jpg",
  "credit": {
   "artist": "Unknown author",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Flatiron_Building_NYC_c1903.jpg"
  }
 },
 {
  "id": "tower-bridge-1892",
  "place": "London, UK",
  "lat": 51.5055,
  "lng": -0.0754,
  "year": 1892,
  "fact": "Tower Bridge halfway built. It opened in 1894.",
  "src": "photos/tower-bridge-1892.jpg",
  "credit": {
   "artist": "Unknown author",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Tower_bridge_works_1892.jpg"
  }
 },
 {
  "id": "first-flight-1903",
  "place": "Kitty Hawk, North Carolina, USA",
  "lat": 36.0146,
  "lng": -75.668,
  "year": 1903,
  "fact": "The Wright brothers' first powered flight lasted 12 seconds.",
  "src": "photos/first-flight-1903.jpg",
  "credit": {
   "artist": "John T. Daniels",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:First_flight3.jpg"
  }
 },
 {
  "id": "machu-picchu-1912",
  "place": "Machu Picchu, Peru",
  "lat": -13.1631,
  "lng": -72.545,
  "year": 1912,
  "fact": "Hiram Bingham's expedition photographed the ruins after clearing the jungle.",
  "src": "photos/machu-picchu-1912.jpg",
  "credit": {
   "artist": "Hiram Bingham III",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Machu_Picchu.png"
  }
 },
 {
  "id": "samarkand-1911",
  "place": "Samarkand, Uzbekistan",
  "lat": 39.6548,
  "lng": 66.9757,
  "year": 1911,
  "fact": "An early color photo by Prokudin-Gorsky, made from three black-and-white exposures.",
  "src": "photos/samarkand-1911.jpg",
  "credit": {
   "artist": "Sergei Prokudin-Gorskii",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Gorskii_21808u.jpg"
  }
 },
 {
  "id": "empire-state-1930",
  "place": "New York City, USA",
  "lat": 40.7484,
  "lng": -73.9857,
  "year": 1930,
  "fact": "Lewis Hine photographed the Empire State Building as it rose, floor by floor.",
  "src": "photos/empire-state-1930.jpg",
  "credit": {
   "artist": "Lewis Hine",
   "license": "CC0",
   "page": "https://commons.wikimedia.org/wiki/File:Empire_State_Building_MET_DP106404.jpg"
  }
 },
 {
  "id": "chicago-fair-1893",
  "place": "Chicago, USA",
  "lat": 41.7897,
  "lng": -87.5836,
  "year": 1893,
  "fact": "The 'White City' of the World's Columbian Exposition.",
  "src": "photos/chicago-fair-1893.jpg",
  "credit": {
   "artist": "William Henry Jackson",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Court_of_Honor,_Looking_West,_William_Henry_Jackson,_1893.jpg"
  }
 },
 {
  "id": "sydney-bridge-1930",
  "place": "Sydney, Australia",
  "lat": -33.8523,
  "lng": 151.2108,
  "year": 1930,
  "fact": "The two halves of the Harbour Bridge arch reaching toward each other.",
  "src": "photos/sydney-bridge-1930.jpg",
  "credit": {
   "artist": "Tyrell Collection",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Sydney_Harbour_Bridge_under_construction.jpg"
  }
 },
 {
  "id": "apollo11-1969",
  "place": "Kennedy Space Center, Florida, USA",
  "lat": 28.6083,
  "lng": -80.6041,
  "year": 1969,
  "fact": "Apollo 11 lifts off for the first Moon landing.",
  "src": "photos/apollo11-1969.jpg",
  "credit": {
   "artist": "NASA; restored by Michel Vuijlsteke",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Apollo_11_Launch2.jpg"
  }
 },
 {
  "id": "rushmore-1932",
  "place": "Mount Rushmore, South Dakota, USA",
  "lat": 43.8791,
  "lng": -103.4591,
  "year": 1932,
  "fact": "Workers carving George Washington's face.",
  "src": "photos/rushmore-1932.jpg",
  "credit": {
   "artist": "Rise Studio, Rapid City, S. Dak. Copyright not renewed.",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Mount_Rushmore2.jpg"
  }
 },
 {
  "id": "dust-bowl-1936",
  "place": "Dallas, South Dakota, USA",
  "lat": 43.2356,
  "lng": -99.5129,
  "year": 1936,
  "fact": "Farm machinery buried by drifting soil during the Dust Bowl.",
  "src": "photos/dust-bowl-1936.jpg",
  "credit": {
   "artist": "Sloan (?)",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Dust_Bowl_-_Dallas,_South_Dakota_1936.jpg"
  }
 },
 {
  "id": "golden-spike-1869",
  "place": "Promontory Summit, Utah, USA",
  "lat": 41.618,
  "lng": -112.551,
  "year": 1869,
  "fact": "The first transcontinental railroad in the US is completed.",
  "src": "photos/golden-spike-1869.jpg",
  "credit": {
   "artist": "Andrew J. Russell / Adam Cuerden",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:East_and_West_Shaking_hands_at_the_laying_of_last_rail_Union_Pacific_Railroad_-_Restoration.jpg"
  }
 },
 {
  "id": "hoover-dam-1934",
  "place": "Hoover Dam, Nevada/Arizona, USA",
  "lat": 36.016,
  "lng": -114.7377,
  "year": 1934,
  "fact": "Intake towers rising at the half-built Hoover Dam.",
  "src": "photos/hoover-dam-1934.jpg",
  "credit": {
   "artist": "National Archives, Herbert Hoover Presidential Library and Museum",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Construction_Intake_Towers_Hoover_Dam_1934.jpg"
  }
 },
 {
  "id": "johnstown-1889",
  "place": "Johnstown, Pennsylvania, USA",
  "lat": 40.3267,
  "lng": -78.922,
  "year": 1889,
  "fact": "Wreckage after a dam failure sent a wall of water through Johnstown.",
  "src": "photos/johnstown-1889.jpg",
  "credit": {
   "artist": "Miscellaneous Items in High Demand, PPOC, Library of Congress",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Johnstown_Flood,_1889-_Landmark_-26_LCCN2005683591.jpg"
  }
 },
 {
  "id": "paris-flood-1910",
  "place": "Paris, France",
  "lat": 48.848,
  "lng": 2.3716,
  "year": 1910,
  "fact": "The Great Flood of Paris turned streets into canals.",
  "src": "photos/paris-flood-1910.jpg",
  "credit": {
   "artist": "Anonyme, photographe",
   "license": "CC0",
   "page": "https://commons.wikimedia.org/wiki/File:Crue_de_la_Seine,_rue_de_Lyon,_12%C3%A8me_arrondissement,_Paris._Inondation_1910._PH8640.jpg"
  }
 },
 {
  "id": "taj-mahal-1865",
  "place": "Agra, India",
  "lat": 27.1751,
  "lng": 78.0421,
  "year": 1865,
  "fact": "Photographed by Samuel Bourne, who spent years documenting India in the 1860s.",
  "src": "photos/taj-mahal-1865.jpg",
  "credit": {
   "artist": "Samuel Bourne",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:KITLV_91973_-_Samuel_Bourne_-_Taj_Mahal_at_Agra_in_India_-_Around_1860.tif"
  }
 },
 {
  "id": "sphinx-1876",
  "place": "Giza, Egypt",
  "lat": 29.9753,
  "lng": 31.1376,
  "year": 1876,
  "fact": "The Great Sphinx, still half-buried in sand.",
  "src": "photos/sphinx-1876.jpg",
  "credit": {
   "artist": "Félix Bonfils",
   "license": "CC0",
   "page": "https://commons.wikimedia.org/wiki/File:Giza,_Sphynx_and_funerary_temple_of_Khafre,_19th_century_pictures,_1875-1877,_photo_8_of_9_-_Archivio_fotografico_Museo_Egizio,_Turin_INV01_011.jpg"
  }
 },
 {
  "id": "titanic-1912",
  "place": "Southampton, UK",
  "lat": 50.897,
  "lng": -1.4,
  "year": 1912,
  "fact": "Titanic leaves Southampton on her first and only voyage.",
  "src": "photos/titanic-1912.jpg",
  "credit": {
   "artist": "Francis Godolphin Osbourne Stuart",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:RMS_Titanic_3.jpg"
  }
 },
 {
  "id": "great-wall-1907",
  "place": "Great Wall, near Beijing, China",
  "lat": 40.3587,
  "lng": 116.0204,
  "year": 1907,
  "fact": "The Great Wall photographed by Herbert Ponting.",
  "src": "photos/great-wall-1907.jpg",
  "credit": {
   "artist": "Herbert Ponting",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Greatwall_large.jpg"
  }
 },
 {
  "id": "rio-1910",
  "place": "Rio de Janeiro, Brazil",
  "lat": -22.897,
  "lng": -43.181,
  "year": 1910,
  "fact": "Avenida Central, the grand new boulevard of Brazil's capital at the time.",
  "src": "photos/rio-1910.jpg",
  "credit": {
   "artist": "Núcleo de digitalização / IMS",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Avenida_Central,_atual_Rio_Branco;_%C3%A0_direita,_o_Monumento_a_Visconde_de_Mau%C3%A1_(007_IMG_2001).jpg"
  }
 },
 {
  "id": "buenos-aires-1894",
  "place": "Buenos Aires, Argentina",
  "lat": -34.6088,
  "lng": -58.3765,
  "year": 1894,
  "fact": "Buildings being demolished to open Avenida de Mayo.",
  "src": "photos/buenos-aires-1894.jpg",
  "credit": {
   "artist": "Unknown author",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Apetura_avenida_mayo.jpg"
  }
 },
 {
  "id": "st-petersburg-1900",
  "place": "Saint Petersburg, Russia",
  "lat": 59.9338,
  "lng": 30.3345,
  "year": 1900,
  "fact": "A horse-drawn tram on Nevsky Prospect.",
  "src": "photos/st-petersburg-1900.jpg",
  "credit": {
   "artist": "Karl Bulla",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Horsetram_on_Nevsky_Prospect_54.jpg"
  }
 },
 {
  "id": "delhi-durbar-1903",
  "place": "Delhi, India",
  "lat": 28.7297,
  "lng": 77.1965,
  "year": 1903,
  "fact": "The Delhi Durbar celebrated Edward VII becoming Emperor of India.",
  "src": "photos/delhi-durbar-1903.jpg",
  "credit": {
   "artist": "Unknown author",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Delhi_Durbar_of_1903_-_LIFE_(2).jpg"
  }
 },
 {
  "id": "colosseum-1846",
  "place": "Rome, Italy",
  "lat": 41.8902,
  "lng": 12.4922,
  "year": 1846,
  "fact": "One of the earliest photographs of the Colosseum.",
  "src": "photos/colosseum-1846.jpg",
  "credit": {
   "artist": "Calvert Jones",
   "license": "CC0",
   "page": "https://commons.wikimedia.org/wiki/File:67._Colosseum,_Rome,_Second_View_MET_DP312745.jpg"
  }
 },
 {
  "id": "capitol-1861",
  "place": "Washington, D.C., USA",
  "lat": 38.8899,
  "lng": -77.0091,
  "year": 1861,
  "fact": "The US Capitol's new dome, unfinished at the start of the Civil War.",
  "src": "photos/capitol-1861.jpg",
  "credit": {
   "artist": "Miscellaneous Items in High Demand, PPOC, Library of Congress",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Capitol_dome_construction_LCCN2009631449.jpg"
  }
 },
 {
  "id": "chicago-fire-1871",
  "place": "Chicago, USA",
  "lat": 41.8837,
  "lng": -87.632,
  "year": 1871,
  "fact": "The Great Chicago Fire burned more than three square miles of the city.",
  "src": "photos/chicago-fire-1871.jpg",
  "credit": {
   "artist": "Clark, C. R. (Charles R.)",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Chicago_Fire_of_1871,_Court_House_Through_Ruins_of_Fifth_National_Bank_(NBY_1364).jpg"
  }
 },
 {
  "id": "moscow-1893",
  "place": "Moscow, Russia",
  "lat": 55.7525,
  "lng": 37.6231,
  "year": 1893,
  "fact": "Red Square's monument to Minin and Pozharsky, photographed by Alexey Mazurin.",
  "src": "photos/moscow-1893.jpg",
  "credit": {
   "artist": "Aleksey Mazurin",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0._%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%B0%D1%8F_%D0%BF%D0%BB._%D0%9F%D0%B0%D0%BC%D1%8F%D1%82%D0%BD%D0%B8%D0%BA_%D0%9C%D0%B8%D0%BD%D0%B8%D0%BD%D1%83_%D0%B8_%D0%9F%D0%BE%D0%B6%D0%B0%D1%80%D1%81%D0%BA%D0%BE%D0%BC%D1%83._(c)%D0%9C%D0%B0%D0%B7%D1%83%D1%80%D0%B8%D0%BD_%D0%90.%D0%A1._1900-%D0%B5%D0%B3%D0%B3_%D0%93%D0%98%D0%9C_e1.jpg"
  }
 },
 {
  "id": "hagia-sophia-1897",
  "place": "Istanbul, Turkey",
  "lat": 41.0086,
  "lng": 28.9802,
  "year": 1897,
  "fact": "Hagia Sophia in Constantinople, as Istanbul was then known.",
  "src": "photos/hagia-sophia-1897.jpg",
  "credit": {
   "artist": "Unknown author",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Hagia_Sophia,_Constantinople,_Turkey,_ca._1897.jpg"
  }
 },
 {
  "id": "angkor-1866",
  "place": "Angkor Wat, Cambodia",
  "lat": 13.4125,
  "lng": 103.867,
  "year": 1866,
  "fact": "John Thomson took some of the first photographs of Angkor Wat.",
  "src": "photos/angkor-1866.jpg",
  "credit": {
   "artist": "Unknown",
   "license": "CC BY 4.0",
   "page": "https://commons.wikimedia.org/wiki/File:Nakhon_Thom_(Angkor_Wat),_Cambodia._Wellcome_L0055705.jpg"
  }
 },
 {
  "id": "nihonbashi-1911",
  "place": "Tokyo, Japan",
  "lat": 35.684,
  "lng": 139.7745,
  "year": 1911,
  "fact": "Crowds visit the brand-new stone Nihonbashi bridge.",
  "src": "photos/nihonbashi-1911.jpg",
  "credit": {
   "artist": "不明 unknown",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:NewlyBuilt_Nihonbashi_1911_Tokyo.jpg"
  }
 },
 {
  "id": "cape-town-1897",
  "place": "Cape Town, South Africa",
  "lat": -33.9227,
  "lng": 18.4209,
  "year": 1897,
  "fact": "Queen Victoria's Diamond Jubilee procession on Adderley Street.",
  "src": "photos/cape-town-1897.jpg",
  "credit": {
   "artist": "Lieut. William J. Frazer, R.N.R., H.M.S. St George. Frazer died on 2 May 1938. Ship photog",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Adderley_Street,_Cape_Town,_South_Africa,_22_June_1897_H0061-L351324055.jpg"
  }
 },
 {
  "id": "jerusalem-1900",
  "place": "Jerusalem",
  "lat": 31.7765,
  "lng": 35.228,
  "year": 1900,
  "fact": "Just inside the Jaffa Gate of Jerusalem's Old City.",
  "src": "photos/jerusalem-1900.jpg",
  "credit": {
   "artist": "American Colony (Jerusalem). Photo Dept., photographer",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:View_inside_Jaffa_Gate,_Jerusalem._between_1898_and_1907._matpc.08601.jpg"
  }
 },
 {
  "id": "amsterdam-1895",
  "place": "Amsterdam, Netherlands",
  "lat": 52.3731,
  "lng": 4.8926,
  "year": 1895,
  "fact": "Dam Square in a photochrom, an early way of turning photos into color prints.",
  "src": "photos/amsterdam-1895.jpg",
  "credit": {
   "artist": "Detroit Publishing Co., under license from Photoglob Zürich",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Dam_square,_Amsterdam,_North_Holland,_the_Netherlands,_1890s.jpg"
  }
 },
 {
  "id": "sagrada-1905",
  "place": "Barcelona, Spain",
  "lat": 41.4036,
  "lng": 2.1744,
  "year": 1905,
  "fact": "Gaudí's Sagrada Família in 1905. It's still being finished today.",
  "src": "photos/sagrada-1905.jpg",
  "credit": {
   "artist": "Baldomer Gili i Roig",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Baldomer_Gili_Roig._La_Sagrada_Fam%C3%ADlia,_1905_Copia_moderna_del_negatiu_original_de_vidre.jpg"
  }
 },
 {
  "id": "neuschwanstein-1897",
  "place": "Neuschwanstein Castle, Germany",
  "lat": 47.5576,
  "lng": 10.7498,
  "year": 1897,
  "fact": "The fairy-tale castle that inspired Disney, only a few years after completion.",
  "src": "photos/neuschwanstein-1897.jpg",
  "credit": {
   "artist": "Unknown author",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Neuschwanstein_Castle_LOC_print_rotated.jpg"
  }
 },
 {
  "id": "havana-1903",
  "place": "Havana, Cuba",
  "lat": 23.1383,
  "lng": -82.3597,
  "year": 1903,
  "fact": "The Paseo del Prado, Havana's grand promenade.",
  "src": "photos/havana-1903.jpg",
  "credit": {
   "artist": "AnonymousUnknown author",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Havana_-_Prado_Avenue.jpg"
  }
 },
 {
  "id": "melbourne-1890",
  "place": "Melbourne, Australia",
  "lat": -37.8143,
  "lng": 144.972,
  "year": 1890,
  "fact": "Collins Street during the 'Marvellous Melbourne' boom years.",
  "src": "photos/melbourne-1890.jpg",
  "credit": {
   "artist": "Possibly Charles Cheney Simpson",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Collins_Street,_near_the_corner_of_Spring_Street.jpg"
  }
 },
 {
  "id": "mexico-city-1907",
  "place": "Mexico City, Mexico",
  "lat": 19.4344,
  "lng": -99.1332,
  "year": 1907,
  "fact": "The Metropolitan Cathedral on the Zócalo, the largest cathedral in the Americas.",
  "src": "photos/mexico-city-1907.jpg",
  "credit": {
   "artist": "(Not given)",
   "license": "Public domain",
   "page": "https://commons.wikimedia.org/wiki/File:Cathedral_of_Mexico_City,_Mexico,_ca.1905-1910_(CHS-667).jpg"
  }
 }
];
