// Builds timescope/world.js — country outlines as flat [lon,lat,...] rings for the offline map.
// Source: world-atlas (Natural Earth 1:110m, public domain). Run: node tools/build-world.mjs
import { writeFileSync } from 'node:fs';

import { mkdirSync } from 'node:fs';
const SRC = 'https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-110m.json';
const topo = await (await fetch(SRC)).json();
mkdirSync(new URL('../timescope/', import.meta.url), { recursive: true });
const [sx, sy] = topo.transform.scale, [tx, ty] = topo.transform.translate;

const arcs = topo.arcs.map(arc => {
  let x = 0, y = 0;
  return arc.map(([dx, dy]) => { x += dx; y += dy; return [x * sx + tx, y * sy + ty]; });
});
const arcPoints = i => (i < 0 ? arcs[~i].slice().reverse() : arcs[i]);
const ring = idxs => idxs.flatMap((i, k) => (k ? arcPoints(i).slice(1) : arcPoints(i)));

const rings = [];
for (const g of topo.objects.countries.geometries) {
  const polys = g.type === 'Polygon' ? [g.arcs] : g.type === 'MultiPolygon' ? g.arcs : [];
  for (const poly of polys) for (const r of poly) {
    const flat = [];
    for (const [lon, lat] of ring(r)) {
      const x = Math.round(lon * 10) / 10, y = Math.round(lat * 10) / 10;
      if (flat.length && flat[flat.length - 2] === x && flat[flat.length - 1] === y) continue;
      flat.push(x, y);
    }
    // Rings that cross the antimeridian (Russia's far east, Fiji) would draw a line across the whole map:
    // shift their western-hemisphere points past +180 so the ring stays continuous.
    if (flat.some((v, i) => i % 2 === 0 && i >= 2 && Math.abs(v - flat[i - 2]) > 180))
      for (let i = 0; i < flat.length; i += 2) if (flat[i] < 0) flat[i] = Math.round((flat[i] + 360) * 10) / 10;
    const antarctic = flat.every((v, i) => i % 2 === 0 || v < -56);   // map is cropped below 58°S
    if (flat.length >= 6 && !antarctic) rings.push(flat);
  }
}
const out = `// Generated by tools/build-world.mjs from Natural Earth 1:110m (public domain).\nwindow.WORLD=${JSON.stringify(rings)};\n`;
writeFileSync(new URL('../timescope/world.js', import.meta.url), out);
console.log(`rings: ${rings.length}, bytes: ${out.length}`);
