// Downloads the photos listed in tools/photos.json (1280px web size) and writes timescope/photos.js with credits.
// Run after tools/commons-search.mjs has cached metadata: node tools/fetch-photos.mjs
import { mkdirSync, readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';

const UA = { 'User-Agent': 'TimescopeGame/1.0 (https://github.com/ladderheroladder/peekmoji)' };
const root = new URL('../', import.meta.url);
const outDir = new URL('timescope/photos/', root);
mkdirSync(outDir, { recursive: true });
const picks = JSON.parse(readFileSync(new URL('tools/photos.json', root), 'utf8'));
const cacheFile = new URL('tools/cache/candidates.json', root);
const cache = existsSync(cacheFile) ? JSON.parse(readFileSync(cacheFile, 'utf8')) : {};
const strip = s => (s || '').replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
const undouble = s => (s.length % 2 === 0 && s.slice(0, s.length / 2) === s.slice(s.length / 2) ? s.slice(0, s.length / 2) : s);   // "Unknown authorUnknown author"
const sleep = ms => new Promise(r => setTimeout(r, ms));

async function lookup(title) {
  if (cache[title]) return cache[title];
  const params = new URLSearchParams({
    action: 'query', format: 'json', titles: title, prop: 'imageinfo', iiprop: 'url|extmetadata', iiurlwidth: '1600',
    iiextmetadatafilter: 'LicenseShortName|Artist'
  });
  const page = Object.values((await (await fetch('https://commons.wikimedia.org/w/api.php?' + params, { headers: UA })).json()).query.pages)[0];
  const ii = page.imageinfo?.[0];
  if (!ii) throw new Error('not found: ' + title);
  return { page: ii.descriptionurl, thumb: ii.thumburl, license: strip(ii.extmetadata?.LicenseShortName?.value), artist: strip(ii.extmetadata?.Artist?.value) };
}

const out = [];
for (const p of picks) {
  const meta = await lookup(p.title);
  let file = readdirSync(outDir).find(f => f.startsWith(p.id + '.'));
  if (!file) {
    let res = await fetch(meta.thumb.replace('/1600px-', '/1280px-'), { headers: UA });
    if (!res.ok) res = await fetch(meta.thumb, { headers: UA });
    if (!res.ok) { console.log(`FAIL ${p.id}: HTTP ${res.status}`); continue; }
    const ext = /png/.test(res.headers.get('content-type')) ? 'png' : 'jpg';
    file = `${p.id}.${ext}`;
    const buf = Buffer.from(await res.arrayBuffer());
    writeFileSync(new URL(file, outDir), buf);
    console.log(`ok ${file} ${(buf.length / 1024).toFixed(0)}KB`);
    await sleep(400);
  }
  const { title, ...rest } = p;
  out.push({ ...rest, src: 'photos/' + file, credit: { artist: undouble(meta.artist).slice(0, 90) || 'Unknown', license: meta.license, page: meta.page } });
}
writeFileSync(new URL('timescope/photos.js', root),
  `// Generated by tools/fetch-photos.mjs from tools/photos.json. Photos via Wikimedia Commons (see credits).\nwindow.TIMESCOPE_PHOTOS = ${JSON.stringify(out, null, 1)};\n`);
console.log(`wrote ${out.length} photos`);
